services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    user: 1000:1000
    userns_mode: keep-id
    volumes:
      - type: bind
        source: /ru-db
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_USER: ru_user
      POSTGRES_PASSWORD: ru_password

  puddle_farm:
    image: puddle_farm
    privileged: true
    shm_size: '1gb'
    restart: always
    ports:
      - 8001:8001
    volumes:
      - type: bind
        source: /ru-static
        target: /frontend
    build:
      dockerfile: ./Dockerfile